import { nanoid } from "nanoid"

export default [
    {
        id: nanoid(),
        name: "Alt_Road 1/2 Zip Jersey Black",
        gender: "men",
        viewAll: "all",
        onSale: true,
        outOfStock: false,
        quntity: 0,
        size: ["m"],
        price: 240.00,
        description: "Aerodynamic race specific jersey",
        altImage: "../src/assets/images/mens-alt1.png",
        mainImage: "../src/assets/images/mens-jersey1.png"
    },
    {
        id: nanoid(),
        name: "Women's Loop Pro Jersey Peach",
        onSale: true,
        outOfStock: false,
        gender: "women",
        quntity: 0,
        size: ["s"],
        price: 290.00,
        description: "Aerodynamic race specific jersey",
        altImage: "../src/assets/images/womens-alt7.png",
        mainImage: "../src/assets/images/womens-jersey7.png"
    },

    {
        id: nanoid(),
        name: "Emblem Pro Hex Jersey Mocha",
        onSale: true,
        outOfStock: false,
        gender: "men",
        quntity: 0,
        size: ["l"],
        price: 150.00,
        description: "Aerodynamic race specific jersey",
        altImage: "../src/assets/images/mens-alt5.png",
        mainImage: "../src/assets/images/mens-jersey5.png"
    },
    {
        id: nanoid(),
        name: "Alt_Road Jersey Dark Grey",
        onSale: true,
        outOfStock: false,
        gender: "women",
        quntity: 0,
        size: ["xl"],
        price: 290.00,
        description: "Aerodynamic race specific jersey",
        altImage: "../src/assets/images/womens-alt4.png",
        mainImage: "../src/assets/images/womens-jersey4.png"
    },
    {
        id: nanoid(),
        name: "Emblem Pro Hex Jersey White",
        onSale: true,
        outOfStock: false,
        gender: "men",
        quntity: 0,
        size: ["l"],
        price: 290.00,
        description: "Aerodynamic race specific jersey",
        altImage: "../src/assets/images/mens-alt6.png",
        mainImage: "../src/assets/images/mens-jersey6.png"
    },
    {
        id: nanoid(),
        name: "Shift Pro Base Jersey Green",
        onSale: true,
        outOfStock: false,
        gender: "men",
        quntity: 0,
        size: ["m"],
        price: 200.00,
        description: "Aerodynamic race specific jersey",
        altImage: "../src/assets/images/mens-alt7.png",
        mainImage: "../src/assets/images/mens-jersey7.png"
    },
    {
        id: nanoid(),
        name: "Shift Pro Base Jersey Orange",
        onSale: true,
        outOfStock: false,
        gender: "men",
        quntity: 0,
        size: ["m"],
        price: 150.00,
        description: "Aerodynamic race specific jersey",
        altImage: "../src/assets/images/mens-alt8.png",
        mainImage: "../src/assets/images/mens-jersey8.png"
    },
    {
        id: nanoid(),
        name: "Emblem Pro Hex Jersey Lime",
        onSale: true,
        outOfStock: false,
        gender: "women",
        quntity: 0,
        size: ["xs"],
        price: 290.00,
        description: "Aerodynamic race specific jersey",
        altImage: "../src/assets/images/womens-alt1.png",
        mainImage: "../src/assets/images/womens-jersey1.png"
    },
    {
        id: nanoid(),
        name: "Alt_Road Jersey Off White",
        onSale: true,
        outOfStock: false,
        gender: "women",
        quntity: 0,
        size: ["xs"],
        price: 150.00,
        description: "Aerodynamic race specific jersey",
        altImage: "../src/assets/images/womens-alt2.png",
        mainImage: "../src/assets/images/womens-jersey2.png"
    },
    {
        id: nanoid(),
        name: "Axis Pro Jersey Pink",
        onSale: true,
        outOfStock: false,
        gender: "men",
        quntity: 0,
        size: ["s"],
        price: 300.00,
        description: "Aerodynamic race specific jersey",
        altImage: "../src/assets/images/mens-alt4.png",
        mainImage: "../src/assets/images/mens-jersey4.png"
    },
    {
        id: nanoid(),
        name: "Emblem Pro Hex Jersey Black",
        onSale: true,
        outOfStock: false,
        gender: "women",
        quntity: 0,
        size: ["s"],
        price: 290.00,
        description: "Aerodynamic race specific jersey",
        altImage: "../src/assets/images/womens-alt3.png",
        mainImage: "../src/assets/images/womens-jersey3.png"
    },
    {
        id: nanoid(),
        name: "Evolve Pro Air Jersey Pink",
        onSale: true,
        outOfStock: false,
        gender: "women",
        quntity: 0,
        size: ["s"],
        price: 290.00,
        description: "Aerodynamic race specific jersey",
        altImage: "../src/assets/images/womens-alt6.png",
        mainImage: "../src/assets/images/womens-jersey6.png"
    },


]